version: '3.9'

services:
 postgres:
  container_name: postgres
  image: postgres
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    PGUSER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
  volumes:
    - ./data:/data/postgres
  ports:
    - "5432:5432"
